### ISSUE TITLE
How to configure it in Azure?

### ISSUE THREAD

**Issue by juandelaoliva** [AdMu2838/analyze-and-generate-images-with-AzureAI#1]
https://github.com/AdMu2838/analyze-and-generate-images-with-AzureAI/blob/204aee897eaec6673e4b6e9e8387c5d3e80d13bb/src/azure-cognitiveservices-computervision.js#L7

Hi! I'm also doing this challenge and I made it work in my local but I can manage to configure the process.env. I got an "undefined"

Did you do any additional step more than just add the vars here?
![image](https://github.com/AdMu2838/analyze-and-generate-images-with-AzureAI/assets/25952223/9e39a290-3dd7-4096-a59e-af219e828e44)

**Comment by AdMu2838** [comment]
Hi, locally you must create an .env file like this. 
<img width="960" alt="Captura de pantalla 2023-11-19 101934" src="https://github.com/AdMu2838/analyze-and-generate-images-with-AzureAI/assets/86539821/64e787c5-92d4-48bf-b183-52b90db48d6d">
